update1

diff --git a/Test_prod/Jenkins_catcherror b/Test_prod/Jenkins_catcherror
--- a/Test_prod/Jenkins_catcherror
+++ b/Test_prod/Jenkins_catcherror
@@ -1,52 +1,51 @@
 pipeline {
-    agent any
     stages {
-        stage ('stage1_a') {
+        stage('STAGE1_a') {
             steps {
-                CatchError('buildResult':'SUCCESS','stageResult':'FAILURE') {
-                sh '''
-                sleep 5
-                exit 1
-                '''
+                catcherror('buildresult':'SUCCESS','stageresult':'FAILURE') {
+                    echo "this is stage1_a"
+                    sh '''
+                    sleep 3
+                    exit 1
+                    '''
                 }
-            } 
-            
+            }
         }
-        stage ('stage1_b'){
+        stage('STAGE1_b') {
             steps {
                 script {
                     try {
-                        sh '''
+                        sh ''' 
                         sleep 2
-                        exit 1
-                        '''
+                        exit 1 '''
                     }
-                catch (err) {
-                    echo "Error caught: ${err}"
-                    currentBuild.reult = 'SUCCESS'
+                    catch (err) {
+                        echo "error caught: ${err}"
+                        currentbuild.result = 'SUCCESS'
                     }
                 }
             }
         }
-        stage ('PARALLEL TESTING') {
+        stage('PARALLEL TESTING') {
             parallel {
-                stage ('WINDOWS TESTING') {
+                stage('WINDOWS TESTING') {
                     steps {
-                        echo "This is WT"
-                    }
+                        echo "WT"
+                        sh 'sleep2'
+                    }                   
                 }
-                stage ('MACOS TESTING') {
+                stage('MACOS TESTING') {
                     steps {
-                        echo "This is MT"
-                    }
+                        echo "MT"
+                        sh 'sleep 2'
+                    }                    
                 }
             }
         }
-        stage ('FINAL') {
+        stage('FINAL') {
             steps {
-                echo "This is finale"
+                echo "Finale"
             }
         }
-        
     }
 }
